export {default as Cart} from './pages/Cart'
export {default as Diet} from './pages/Diet'
export {default as Home} from './pages/Home'
export {default as Shop} from './pages/Shop'
export {default as Workout} from './pages/Workout'
export {default as SignInPage} from './pages/SignInPage'
export {default as SignUpPage} from './pages/SignUpPage'
export {default as CategoryPage} from './pages/CategoryPage'
export {default as Header} from './Boilerplate/Header'
export {default as Footer} from './Boilerplate/Footer'

// export {default as Items} from './pages/Items'
